extends "res://scripts/V83UpgradeTestBase.gd"
const RESEARCH=preload("res://scripts/ResearchAllocationService.gd")
func _init() -> void:_run.call_deferred()
func _run() -> void:
	var main=await make_main("aurelia",3)
	var first: String=main._deployed_hero_ids()[0]
	main.hero_skill_tree[first]={"offense":6,"survival":6,"utility":6}
	main.set_meta("growth_hero_id",first);main._build_growth_screen();await settle()
	var open: Button=main.find_child("OpenResearchAllocation",true,false)
	check(open!=null,"growth entry exists")
	if open==null:await dispose(main);done("v834_growth_ui");return
	open.pressed.emit();await settle()
	check(main.active_screen=="research_allocation","opens allocation screen")
	var before: Dictionary=economic(main)
	var confirm: Button=main.find_child("ResearchConfirm",true,false)
	check(confirm!=null and confirm.disabled,"no immediate commit button")
	var attack: SpinBox=main.find_child("ResearchDraft_offense",true,false)
	var survival: SpinBox=main.find_child("ResearchDraft_survival",true,false)
	attack.value=10;survival.value=3;await settle()
	check(economic(main)==before,"editing controls is draft only")
	main.find_child("ResearchPreview",true,false).pressed.emit();await settle()
	check(not confirm.disabled and confirm.is_visible_in_tree(),"explicit preview unlocks confirmation")
	check(before==economic(main),"preview cannot alter progression")
	survival.value=2;await settle();check(confirm.disabled,"changing draft invalidates preview")
	main.find_child("ResearchPreview",true,false).pressed.emit();await settle()
	confirm.pressed.emit();await settle()
	check(main.active_screen=="growth" and main.hero_skill_tree[first]=={"offense":10,"survival":2,"utility":6},"confirmation commits exact preview")
	main._open_research_allocation(first);await settle()
	var after: Dictionary=economic(main)
	main.find_child("ResearchResetDraft",true,false).pressed.emit();await settle()
	check(main.find_child("ResearchDraft_offense",true,false).value==0 and after==economic(main),"reset is draft only")
	main.find_child("ResearchCancel",true,false).pressed.emit();await settle()
	check(after==economic(main),"cancel keeps applied allocation")
	main._open_practice_screen();await settle()
	var mode: OptionButton=main.find_child("PracticeLevelMode",true,false)
	var level: SpinBox=main.find_child("PracticeMatchLevel",true,false)
	check(mode!=null and mode.selected==0 and not level.editable,"actual growth is default")
	mode.select(1);mode.item_selected.emit(1);level.value=60
	check(level.editable,"matching enables explicit level choice")
	main.find_child("PracticeStart_gold_rush",true,false).pressed.emit();await settle()
	check(main.challenge_session!=null and main.challenge_session.entry_context.level_mode=="matched","button starts selected matching mode")
	main._build_lobby_screen();await settle()
	check(not main.has_meta("practice_level_override"),"navigation clears overlay")
	await dispose(main)
	done("v834_growth_ui")
