using System;
using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;
using L=Eternal.UnityMigration.LegacyFeatureCatalog;

namespace Eternal.UnityMigration.Editor
{
    public static class LegacyFeatureVerification
    {
        public static void Run()
        {
            var checks=new JArray();bool all=true;
            void Check(string name,bool condition){checks.Add(new JObject{{"name",name},{"passed",condition}});all&=condition;if(!condition)Debug.LogError("LEGACY_PORT_CHECK_FAILED: "+name);}
            try
            {
                var catalog=new OriginalCombatCatalog(OriginalCatalog.Required("hero-catalog").text);var payload=NativePlayerSession.NewPayload(catalog,"aurelia");payload["unknown_future_notes"]=new JObject{{"keep",new JArray(1,"old",true)}};
                foreach(var id in catalog.HeroIds.Where(id=>(string)catalog.Hero(id)["faction"]=="aurelia"))payload["hero_progress"][id]["level"]=80;
                JObject stored=null;var game=new GameStateCommands(catalog,payload,s=>{stored=(JObject)s.DeepClone();return true;});long now=L.Now;
                var original83=(JObject)payload.DeepClone();foreach(string key in L.Array(L.Data["save_fields"]).Values<string>())if(original83[key]==null)original83[key]=JValue.CreateNull();var imported83=NativePlayerSession.ImportPayload(catalog,original83);
                Check("all 83 original save fields copied without discarding values",L.Array(L.Data["save_fields"]).Count==83&&L.Array(L.Data["save_fields"]).Values<string>().All(key=>JToken.DeepEquals(original83[key],imported83[key])));
                var oracleWorld=new LegacyWorldWar(new JObject(),"aurelia",now);
                foreach(var plan in L.Object(L.Data["oracle"]?["world_plans"]).Properties())
                {string[] pair=plan.Name.Split(':');var actual=oracleWorld.Quote(new Vector2Int(int.Parse(pair[0]),int.Parse(pair[1])));Check("actual Godot BFS/march oracle "+plan.Name,L.Object(plan.Value).Properties().All(p=>JToken.DeepEquals(p.Value,actual[p.Name]))&&((JObject)plan.Value).Count>0==actual.Count>0);}
                Check("original definitions: 100 guide, 6 daily, 6 weekly, 18 achievements",game.GoalRows("guide").Count==100&&game.GoalRows("daily").Count==6&&game.GoalRows("weekly").Count==6&&game.GoalRows("achievement").Count==18);
                for(int i=1;i<=5;i++)Check("native hunt receipt "+i,game.SettleUnityPack(i,20,10,24).Ok);
                var context=game.GoalContext("guide");long gold=game.WalletGold;Check("claim sequential guide",game.ClaimGoal("guide","guide_001",context).Ok&&game.WalletGold==gold+120);gold=game.WalletGold;Check("duplicate goal cannot mint currency",!game.ClaimGoal("guide","guide_001",context).Ok&&game.WalletGold==gold);Check("locked guide cannot skip chapters",!game.ClaimGoal("guide","guide_100",context).Ok);
                var daily=game.ReserveChallenge("daily","gold_rush",now);var session=new LegacyChallengeSession((long)daily.Details["serial"],(JObject)daily.Details["entry"]);
                for(int i=0;i<3;i++){var enemy=new Combatant{Serial=i+1,Hp=100,MaxHp=100};session.Register(new[]{enemy});session.ObserveHp(enemy,100,0);session.CompleteWave(0,10);}
                Check("wave objective earns a native runtime receipt",session.State==LegacyChallengeSession.Outcome.Won);gold=game.WalletGold;Check("daily reward schedule and completion quota",game.FinishChallenge(session,now).Ok&&game.WalletGold==gold+950&&L.N(game.ChallengeStatus(now)["daily_runs"])==1);gold=game.WalletGold;Check("duplicate dungeon settlement rejected",!game.FinishChallenge(session,now).Ok&&game.WalletGold==gold);Check("unproven tier cannot sweep",!game.SweepDaily("gold_rush",now).Ok);
                var nextDay=now+86400;Check("proven same faction/mode/tier unlocks next-day sweep",game.SweepDaily("gold_rush",nextDay).Ok);Check("clock rollback cannot refill dungeon",!game.ReserveChallenge("daily","gold_rush",now).Ok);
                var tower=game.ReserveChallenge("tower","floor",nextDay);var towerSession=new LegacyChallengeSession((long)tower.Details["serial"],(JObject)tower.Details["entry"]);
                for(int i=0;i<2;i++){towerSession.Register(new[]{new Combatant{Serial=i+1,Hp=100,MaxHp=100}});towerSession.CompleteWave(0,10);}Check("tower clear advances once",game.FinishChallenge(towerSession,nextDay).Ok&&L.N(game.ChallengeStatus(nextDay)["floor"])==2&&L.N(game.ChallengeStatus(nextDay)["best_floor"])==1);
                var week=game.ReserveChallenge("weekly","score",nextDay);var weekly=new LegacyChallengeSession((long)week.Details["serial"],(JObject)week.Details["entry"]);var boss=new Combatant{Serial=1,Hp=1000,MaxHp=1000};weekly.Register(new[]{boss});weekly.ObserveHp(boss,1000,900);weekly.ObserveHp(boss,1000,900);weekly.ObserveHp(boss,950,850);Check("weekly counts new HP loss only, not repeats/healing",weekly.Damage==150);weekly.Advance(90,10);gold=game.WalletGold;Check("weekly actual damage settlement",game.FinishChallenge(weekly,nextDay).Ok&&game.WalletGold==gold+1600&&L.N(game.ChallengeStatus(nextDay)["weekly_best"])==150);
                Check("initialize exact original 1600-cell world",game.InitializeWar().Ok&&L.Object(game.WarView()["world"]?["cells"]).Count==1600);var quote=game.WarQuote(3,9);Check("BFS own-route and original 8-rations-per-tile",L.Array(quote["path"]).Count==3&&L.N(quote["ration_cost"])==16);Check("march persists without instant capture",game.WarCommand("march",3,9,expectedRevision:(long)quote["revision"],now:now).Ok&&(string)game.WarView()["world"]["cells"]["3:9"]["owner"]=="neutral");Check("arrival commits ownership once",game.AdvanceWar(now+9).Ok&&(string)game.WarView()["world"]["cells"]["3:9"]["owner"]=="aurelia");long captures=L.N(game.WarView()["world"]["captured_count"]);game.AdvanceWar(now+10);Check("repeated arrival cannot double capture",L.N(game.WarView()["world"]["captured_count"])==captures);Check("enemy sanctuary cannot be attacked",game.WarQuote(18,10)["error"].ToString().Length>0);
                var season=game.WarView(now+29*86400);Check("season contribution reward available only after active period",L.Flag(season["reward"]?["claimable"]));Check("season reward once",game.WarCommand("claim_season_reward",now:now+29*86400).Ok&&!game.WarCommand("claim_season_reward",now:now+29*86400).Ok);
                var marketPayload=NativePlayerSession.NewPayload(catalog,"aurelia");marketPayload["loot_inventory"]=new JArray(OriginalEquipmentRules.Normalize(new JObject{{"id","trade_sword"},{"slot","weapon"},{"rarity","희귀"},{"set","개척자"},{"name","검증 검"},{"level",1},{"origin","hunt"}}));var trade=new GameStateCommands(catalog,marketPayload,_=>true);Check("real inventory escrow listing",L.Flag(trade.MarketCommand("list",new JObject{{"item_id","trade_sword"},{"price",100}}).Details["ok"])&&trade.Inventory().Count==0);string listing=(string)trade.MarketView()["listings"][0]["id"];Check("self purchase rejected",!L.Flag(trade.MarketCommand("buy",new JObject{{"listing_id",listing}}).Details["ok"]));Check("cancel returns to delivery, not duplicate bag",L.Flag(trade.MarketCommand("cancel",new JObject{{"listing_id",listing}}).Details["ok"])&&trade.Inventory().Count==0&&L.Array(trade.MarketView()["account"]?["deliveries"]).Count==1);Check("claim delivery once",L.Flag(trade.MarketCommand("claim").Details["ok"])&&trade.Inventory().Count==1&&!L.Flag(trade.MarketCommand("claim").Details["ok"]));
                marketPayload["raid_crystals"]=100;marketPayload["gear_auto_equip"]=false;var workshop=new GameStateCommands(catalog,marketPayload,_=>true);Check("workshop proposal escrow",workshop.Workshop("trade_sword","preview",family:"assault").Ok&&workshop.RaidCrystals==88);Check("workshop choose and extract",workshop.Workshop("trade_sword","choose",0).Ok&&workshop.Workshop("trade_sword","extract",0).Ok&&workshop.Inventory().Count==2&&workshop.RaidCrystals==70);string crystal=(string)workshop.Inventory().First(i=>(string)i["item_type"]=="option_crystal")["id"];Check("crystal implant consumes exactly one item",workshop.Workshop("trade_sword","apply",crystalId:crystal).Ok&&workshop.Inventory().Count==1&&workshop.RaidCrystals==62);
                Check("save complete combat preset",game.SaveCombatPreset(0).Ok);var preset=game.CombatPreset(0);gold=game.WalletGold;Check("apply preset references existing gear without currency mint",game.ApplyCombatPreset(0,preset).Ok&&game.WalletGold==gold);
                var idlePayload=NativePlayerSession.NewPayload(catalog,"aurelia");idlePayload["last_idle_timestamp"]=now-12*3600;var idle=new GameStateCommands(catalog,idlePayload,_=>true);Check("offline reward bounded to 8h / 5 stages / 32 rolls",idle.CalculateOffline(now).Ok&&L.N(idle.Snapshot()["unity_last_offline"]?["seconds"])==28800&&L.N(idle.Snapshot()["unity_last_offline"]?["stages"])<=5&&L.N(idle.Snapshot()["unity_last_offline"]?["gear_rolls"])<=32);gold=idle.WalletGold;var unclaimed=idle.Snapshot()["unclaimed_gold"].DeepClone();idle.CalculateOffline(now);Check("repeat offline calculation cannot replay rewards",JToken.DeepEquals(unclaimed,idle.Snapshot()["unclaimed_gold"])&&idle.WalletGold==gold);
                var failed=new GameStateCommands(catalog,payload,_=>false);var reservation=failed.ReserveUnityRaid("gray_meadow");Check("failed write retains one candidate and blocks mutations",reservation.Ok&&reservation.SavePending&&!failed.ClaimDaily(L.Day(now)).Ok);var practice=new GameStateCommands(catalog,payload,_=>true){PracticeActive=true};Check("practice blocks all progression commands",!practice.InitializeWar().Ok&&!practice.ClaimDaily(L.Day(now)).Ok&&!practice.MarketCommand("claim").Ok);
                Check("unknown Godot payload data retained",JToken.DeepEquals(payload["unknown_future_notes"],game.Snapshot()["unknown_future_notes"]));
                var real=game.ReserveChallenge("daily","boss_hunt",nextDay+86400);var runtime=new HuntingSimulation(1,9514,game);var battle=new LegacyChallengeSession((long)real.Details["serial"],(JObject)real.Details["entry"]);runtime.AttachChallenge(battle);int ticks=0;while(battle.Running&&ticks++<1300)runtime.Step(.05);Check("actual native 10-hero dungeon runs to victory without field rewards",battle.State==LegacyChallengeSession.Outcome.Won&&runtime.Gold==0&&runtime.PacksCleared==0&&runtime.Battle.Heroes.Count==10);
                var ledger=battle.Report();Check("ten actor ledger credits only settled HP loss",L.Array(ledger["actors"]).Count==10&&L.Array(ledger["actors"]).OfType<JObject>().Sum(r=>L.N(r["damage"]))+L.N(ledger["support_damage"])+L.N(ledger["unknown_damage"])==battle.Damage);
                var link=new GameStateCommands(catalog,payload,_=>true);link.InitializeWar();link.WarCommand("set_stance",context:"guard");long sharedGold=link.WalletGold,sharedGems=link.WalletGems;
                Check("same-account faction switch keeps wallets and selects ten own heroes",link.SwitchAccountFaction("noxfera").Ok&&link.WalletGold==sharedGold&&link.WalletGems==sharedGems&&link.DeployedHeroes().Count==10&&link.DeployedHeroes().All(link.IsFactionHero));
                Check("faction world bank restores territory and stance",link.SwitchAccountFaction("aurelia").Ok&&(string)link.WarView()["world"]["battle_stance"]=="guard"&&link.WalletGold==sharedGold);
                var once=link.WarCommand("set_stance",context:"balanced",requestId:"ui-test-once");long revision=L.N(link.WarView()["revision"]);var replay=link.WarCommand("set_stance",context:"balanced",requestId:"ui-test-once");Check("world command replay cannot repeat revision or resource cost",once.Ok&&replay.Ok&&L.Flag(replay.Details["replayed"])&&L.N(link.WarView()["revision"])==revision);
                Check("world receipt rejects payload substitution",!link.WarCommand("set_stance",context:"assault",requestId:"ui-test-once").Ok);
                Check("disconnect blocks world commands and catch-up",link.SetWorldConnection(false).Ok&&!link.WarCommand("set_stance",context:"guard").Ok&&!link.AdvanceWar().Ok);
                Check("local reconnect restores authority without cached world replacement",link.SetWorldConnection(true).Ok&&link.WarCommand("set_stance",context:"guard").Ok);
                link.WorldClockSample(10,true);link.WorldClockSample(30);Check("source clock correction limit 0.75 and warning above eight seconds",Math.Abs(L.F(link.Snapshot()["world_authority"]?["server_time_offset_seconds"])-10.75)<.0001&&L.Flag(link.Snapshot()["world_authority"]?["unity_clock_warning"]));
                string profilePath=Path.GetFullPath(Path.Combine(Application.dataPath,"../../../../validation/native-linked-profile-test-"+Guid.NewGuid().ToString("N")+"/aurelia.json"));var linkedStore=new NativeSessionStore(profilePath,"aurelia");Check("native v2 initial profile persists",linkedStore.Write(payload));var linked=new NativePlayerSession(catalog,payload,linkedStore);Check("linked faction persists under its original account path",linked.State.SwitchAccountFaction("noxfera").Ok&&!linked.State.SavePending&&(string)linkedStore.Read().Payload?["selected_faction"]=="noxfera");
                var reloaded=linkedStore.Read();var resumed=new NativePlayerSession(catalog,reloaded.Payload,linkedStore);Check("linked account can round-trip after reload without new wallet",resumed.State.SwitchAccountFaction("aurelia").Ok&&resumed.State.WalletGold==L.N(payload["wallet_gold"]));
                var legacyEnvelope=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText(profilePath));legacyEnvelope["version"]=1;legacyEnvelope.Remove("sha256");legacyEnvelope["sha256"]=LegacySaveCodec.Hash(legacyEnvelope.ToString(Newtonsoft.Json.Formatting.None));File.WriteAllText(profilePath,legacyEnvelope.ToString(Newtonsoft.Json.Formatting.None));Check("native v1 profiles remain readable",new NativeSessionStore(profilePath,"aurelia").Read().Ok);
                var tutorial=new GameStateCommands(catalog,payload,_=>true);for(int pack=1;pack<=5;pack++)tutorial.SettleUnityPack(pack,1,1);Check("passive hunt XP cannot fake deliberate tutorial growth",L.N(tutorial.TutorialStatus()["step"])==4&&!L.Flag(tutorial.Snapshot()["tutorial_actions"]?["growth"]));Check("deliberate research advances tutorial",tutorial.UpgradeResearch("leonhardt","survival").Ok&&L.N(tutorial.TutorialStatus()["step"])==5);Check("actual raid reservation completes opening guide",tutorial.ReserveUnityRaid("gray_meadow").Ok&&L.Flag(tutorial.TutorialStatus()["complete"]));
                var exact=new RaidSimulation("gray_meadow",20,9514);var knight=exact.Battle.Heroes[0];knight.Position=exact.Boss.Position+Vector2.left;exact.Battle.RaidControlWindow=true;exact.Battle.Kits[knight.Id].Cooldowns["a2"]=0;Check("named raid skill control casts a2 instead of substituting a1",exact.ManualCastSlot(knight.Id,"a2")&&exact.Battle.Kits[knight.Id].Cooldowns["a2"]>0&&!exact.CanManualCastSlot(knight.Id,"invalid"));
                var corruptMarket=new LegacyEquipmentMarket(new JObject{{"accounts",new JObject{{"player_local",new JObject{{"inventory",new JArray(new JObject{{"id",new JObject()}})}}}}}});Check("malformed escrow item fails without crashing",corruptMarket.LoadError.Length>0);
                var queueRoot=new JObject();var queueWorld=new LegacyWorldWar(queueRoot,"aurelia",now);var queuedTarget=new Vector2Int(6,10);queueWorld.Tile(queuedTarget)["owner"]="aurelia";
                var npc=new JObject{{"force_id","queue_npc"},{"player_name","기존 공격대"},{"faction","noxfera"},{"power",100000},{"fatigue",0},{"stance","balanced"},{"is_npc",true},{"squad",LegacyWarBattle.Garrison("noxfera",new Vector2Int(8,10),"plain",100000)}};
                Check("world attack queue rejects duplicate forces",LegacyWorldAttackQueue.Enqueue(queueWorld,queuedTarget,npc)&&!LegacyWorldAttackQueue.Enqueue(queueWorld,queuedTarget,npc));
                var queuedReport=LegacyWorldAttackQueue.Process(queueWorld,queuedTarget,new JObject(),now);Check("imported queued NPC attack resolves real defending squads",L.Array(queuedReport["battle_summaries"]).Count>0&&L.Array(queueWorld.Conflict["attack_queues"]?["6:10"]).Count==0);
                for(int n=0;n<8;n++){npc["force_id"]="queue_"+n;LegacyWorldAttackQueue.Enqueue(queueWorld,queuedTarget,npc);}npc["force_id"]="queue_over_cap";Check("world FIFO queue bounded to original eight forces",!LegacyWorldAttackQueue.Enqueue(queueWorld,queuedTarget,npc)&&L.Array(queueWorld.Conflict["attack_queues"]?["6:10"]).Count==8);
                var pendingField=(JObject)payload.DeepClone();pendingField["unity_pending_loot"]=new JArray(new JObject{{"id","pending_test"}});
                var pendingState=new GameStateCommands(catalog,pendingField,_=>true);var challengeOnly=new HuntingSimulation(20,9514,pendingState);var detachedReceipt=new LegacyChallengeSession(1,new JObject{{"mode","daily"},{"variant","gold_rush"},{"run_index",0}});challengeOnly.AttachChallenge(detachedReceipt);challengeOnly.Step(.05);Check("challenge clock and movement ignore field equipment delivery pause",pendingState.HasDeferredUnityLoot&&challengeOnly.Ticks>0&&challengeOnly.SetManualMovement(Vector2.right));
            }
            catch(Exception e){all=false;checks.Add(new JObject{{"exception",e.ToString()}});Debug.LogException(e);}
            string output=Path.GetFullPath(Path.Combine(Application.dataPath,"../../../../native-legacy-feature-report-20261010.json"));File.WriteAllText(output,new JObject{{"passed",all},{"count",checks.Count},{"checks",checks}}.ToString());Debug.Log("NATIVE_LEGACY_FEATURE_REPORT: "+output+" · "+all+" · "+checks.Count);EditorApplication.Exit(all?0:1);
        }
    }
}
