extends 'res://tests/support/V83UpgradeTestBase.gd'
func _init() -> void:run.call_deferred()
func run() -> void:
	var authored: Dictionary=JSON.parse_string(FileAccess.get_file_as_string('res://assets/mobile25d/floor/material.json'))
	check(absf(authored.moss_fraction-.18)<.00001 and authored.moss_outside_crack_band==0,'eighteen percent moss remains entirely inside authored crack bands')
	check(absf(authored.patina_fraction_in_cracks-.25)<.00001,'twenty-five percent of actual cracks carry patina')
	check(int(authored.texture_size[0])==1024 and int(authored.texture_size[1])==1024 and int(authored.runtime_textures)==4,'floor uses four packed 1024 runtime textures')
	var main=await make_main('aurelia',10);main.combat_effects_enabled=true
	main._build_combat_screen();await settle()
	if is_instance_valid(main.combat_timer):main.combat_timer.stop()
	var field=main.combat_labels.terrain;field.set_process(false)
	var floor: MeshInstance3D=field.world.get_node('PBRStoneSlabs1024')
	check(floor.material_override is ShaderMaterial and floor.material_override.shader.resource_path=='res://shaders/FinalStonePBR.gdshader','real game floor uses final PBR shader')
	check(floor.material_override.get_shader_parameter('stone_art').get_size()==Vector2(1024,1024),'runtime final albedo retains 1024 detail')
	check(is_equal_approx(floor.material_override.get_shader_parameter('moss_glow'),.25),'Ultra floor moss glow reaches .25')
	check(floor.material_override.get_shader_parameter('tile_scale').is_equal_approx(Vector2(11.111111,8.75)),'closer hunt camera uses two-times larger complete 1024 slabs')
	var circle=field.rune_ground;circle.set_process(false)
	check(circle.stone_material.get_shader_parameter('rune_count')==12 and circle.get_meta('falling_leaves')==20,'twelve runes and twenty bounded leaves')
	check(is_equal_approx(circle.moss_light.light_energy,.9) and not circle.moss_light.shadow_enabled,'real moss point light reaches .9 without a new shadow pass')
	var light: DirectionalLight3D=field.world.get_node('AutoMapSun')
	var environment: Environment=field.world.get_node('Atmosphere').environment
	check(is_equal_approx(light.light_energy,1.0) and is_equal_approx(environment.glow_intensity,.6) and is_equal_approx(environment.glow_strength,.9),'Ultra lighting profile reaches the real map')
	main.combat_running=false;var circle_clock: float=circle.elapsed;circle._process(.5)
	check(is_equal_approx(circle_clock,circle.elapsed),'paused hunt does not animate leaves or runes')
	main.combat_running=true;circle._process(.1)
	check(circle.elapsed>circle_clock,'live hunt advances the shared ground clock')
	main.combat_effects_enabled=false;circle._process(.1)
	check(not circle.visible,'effects-off hides circle and its child point light')
	main.combat_running=false;main.combat_effects_enabled=true;main._build_raid_screen();await settle();main._start_raid();await settle()
	var view=main.content_root.get_node('PortraitRaidView');field=view.battlefield_3d;field.set_process(false)
	floor=field.world.get_node('PBRStoneSlabs1024')
	check(floor.material_override.get_shader_parameter('tile_scale').is_equal_approx(Vector2(5.555556,4.375)),'wider raid camera uses four-times larger complete 1024 slabs')
	var mood=field.world.get_node('RaidDesign');mood.set_process(false)
	check(not view.boss_motion.decorative_ground_enabled and is_instance_valid(view.boss_motion.actor),'final raid seal replaces old ground ring while retaining boss motion observer')
	var rng: int=main.loot_rng.state;var hp: int=main.raid_boss_hp;var clock: float=main.raid_elapsed
	mood._process(.1)
	var boss: Vector2=field.raid_to_world(main.raid_boss_position)
	check(Vector2(mood.seal.position.x,mood.seal.position.z).distance_to(boss)<.001,'raid seal follows the actual boss feet')
	check(is_equal_approx(mood.material.get_shader_parameter('glow'),.7) and is_equal_approx(mood.material.get_shader_parameter('pulse_period'),1.0),'raid seal uses glow .7 and one-second brightness pulse')
	mood.set_battle_mood(3,true);mood._process(.1)
	check(main.loot_rng.state==rng and main.raid_boss_hp==hp and main.raid_elapsed==clock,'environment cannot alter raid rules, HP or gameplay RNG')
	check(is_equal_approx(view.telegraph.WARNING_ALPHA,.6) and view.telegraph.WARNING_RED==Color('#e94c43'),'actual boss warning uses readable red .6')
	main.raid_running=false;var held: float=mood.elapsed;mood._process(.5)
	check(is_equal_approx(mood.elapsed,held),'paused raid freezes its decorative ground seal')
	main.combat_effects_enabled=false;mood._process(.1)
	check(not mood.visible,'effects-off removes raid ground ornament')
	await dispose(main);done('FINAL_ENVIRONMENT')
