extends 'res://tests/support/V83UpgradeTestBase.gd'
const PAINT=preload('res://scripts/art/MobileReliefPilot.gd')
const STYLE=preload('res://scripts/combat/CombatNumberStyle.gd')
func _init() -> void:run.call_deferred()
func run() -> void:
	var camera:=Camera3D.new();root.add_child(camera)
	var source=HeroSpriteFactory.create_hero('leonhardt');root.add_child(source);source.set_process(false);source.speed_scale=1
	var paint:=PAINT.new();root.add_child(paint);check(paint.bind(source,true),'real hero binds the final paint material')
	source.play_idle('right');paint.present(camera,1,Color.WHITE,.5,true,Vector2.ZERO,{},false)
	check(paint.material_override.get_shader_parameter('outline_px')==2.0 and paint.material_override.get_shader_parameter('outline_opacity')==.6,'hero silhouette has 2px black 60 percent outline')
	check(paint.position.length()<=2.0/86.4+.00001,'breathing cannot exceed 2px or scale the original body')
	paint.timeline.release('attack_1',.15);paint.present(camera,1,Color.WHITE,0,true,Vector2.ZERO,{},false)
	check(paint._echoes.layers.size()==2 and paint._echoes.layers[0].visible and paint._echoes.layers[1].visible,'both contact afterimages draw at the real release')
	check(is_equal_approx(paint._echoes.layers[0].material_override.get_shader_parameter('opacity'),.5),'contact afterimage starts at alpha .5')
	paint._echoes.present(paint,'attack_1',.5,paint.timeline.sequence,paint._echoes.started+.199,true)
	check(paint._echoes.layers[0].visible,'trail remains before .20 seconds')
	paint._echoes.present(paint,'attack_1',.5,paint.timeline.sequence,paint._echoes.started+.201,true)
	check(not paint._echoes.layers[0].visible and not paint._echoes.layers[1].visible,'both trail meshes expire after .20 seconds')
	paint.timeline.hit(Vector2.RIGHT)
	check(paint._contact_flash_at(100000,false)>.5,'a fresh hit starts the white contact flash')
	paint.timeline.sample({},false,false,.08,false)
	check(paint._contact_flash_at(140001,false)==0.0,'40ms wall-time flash expires even while hitstop holds the pose')
	for i in 100:paint.timeline.hit(Vector2.RIGHT);paint._contact_flash_at(150000,false)
	check(paint._contact_flash_at(150001,false)==0.0,'burst hits cannot extend the expired flash into a white silhouette')
	paint.free();source.free();camera.free()
	check(STYLE.font_size('damage')==16 and STYLE.PALETTES.critical[0]==Color('#ffd700'),'damage face grows and crit uses gold')
	var main=await make_main('aurelia',10);main.combat_effects_enabled=true;main._build_combat_screen();await settle();main.combat_running=true
	if is_instance_valid(main.combat_timer):main.combat_timer.stop()
	var field=main.combat_labels.terrain;field.set_process(false);field._process(0)
	var actor=main.enemy_wave_sprites[0];field.contact_feedback(false,main.roaming_hunt.enemy_position(0),actor)
	var original_tint: Color=actor.modulate;actor.self_modulate=Color('#ffb0b0');field._process(0)
	check(field.actors[actor.get_instance_id()].modulate==original_tint,'3D paint ignores the source controller second red hit blink')
	check(field._contact_holds[actor.get_instance_id()]-Time.get_ticks_usec()<=80000 and field._contact_holds[actor.get_instance_id()]>Time.get_ticks_usec(),'ordinary hit holds only the victim for 80ms')
	check(is_equal_approx(Engine.time_scale,1) and field.visual_running(),'ordinary hit keeps the battle and translation moving')
	var hold: int=field._contact_holds[actor.get_instance_id()]
	for i in 100:field.contact_feedback(false,main.roaming_hunt.enemy_position(0),actor)
	check(field._contact_holds[actor.get_instance_id()]==hold,'100 simultaneous hits cannot extend victim hitstop')
	var observer=main.presentation_runtime.get_node('HeroCelebrationFeedback')
	observer._process(.3) # Establish the initial fixture levels before awarding XP.
	var old: int=int(main.hero_progress[main.deployed_heroes[0].id].level)
	main._grant_hero_xp(main._hero_xp_to_next(old)*main.deployed_heroes.size())
	var rng: int=main.loot_rng.state;var state:=economic(main);observer._process(.3)
	check(int(main.hero_progress[main.deployed_heroes[0].id].level)>old and not field.hunt_overlay.celebrations.is_empty(),'actual XP level changes trigger the 12-particle observer')
	check(main.loot_rng.state==rng and economic(main)==state,'celebration detection cannot grant XP or consume combat/loot RNG')
	check(field.hunt_overlay.celebrations.size()<=4,'simultaneous levelups keep a bounded canvas budget')
	main.combat_effects_enabled=false;field.hunt_overlay._process(.1)
	check(field.hunt_overlay.celebrations.is_empty(),'effects-off retires level particles')
	main._build_raid_screen();await settle();main._start_raid();main.combat_timer.stop();field=main.content_root.get_node('PortraitRaidView').battlefield_3d;field.set_process(false);field._process(0)
	check(absf(field._actor_height(main.raid_boss_sprite,false)*field.size.y/field.camera.size-179.2)<.00001,'raid boss is 128px times the final 1.4 scale')
	main.combat_effects_enabled=true
	var boss_tint: Color=main.raid_boss_sprite.modulate
	main._apply_raid_damage(50,str(main.deployed_heroes[0].id))
	check(main.raid_boss_sprite.modulate==boss_tint and main.skill_fx_layer.find_children('CombatImpact','Control',true,false).is_empty(),'raid hits use the 3D contact path without legacy tint or duplicate impact panels')
	main.raid_running=false;main.presentation_runtime.contact_time.restore();await dispose(main);done('FINAL_HERO_FEEDBACK')
